// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtkRd9QdDsSxjfc9_xweFqjM4WKg7msZg',
    appId: '1:597612844501:web:8cec1683e37794c236595c',
    messagingSenderId: '597612844501',
    projectId: 'test-map-realtime-fire',
    authDomain: 'test-map-realtime-fire.firebaseapp.com',
    storageBucket: 'test-map-realtime-fire.appspot.com',
    measurementId: 'G-NKHZBPEN6Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjfcweemukNupu-mqxBDl-WbzxET4SiNA',
    appId: '1:597612844501:android:1d98c08f70aa599736595c',
    messagingSenderId: '597612844501',
    projectId: 'test-map-realtime-fire',
    storageBucket: 'test-map-realtime-fire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNBtdy9dUa1DjlgHZ57kJkW1pK9sr_BM',
    appId: '1:597612844501:ios:7de984de96f5a6d136595c',
    messagingSenderId: '597612844501',
    projectId: 'test-map-realtime-fire',
    storageBucket: 'test-map-realtime-fire.appspot.com',
    iosClientId: '597612844501-qfobih9qn7qnff5mht99c4hj0oe4ijoh.apps.googleusercontent.com',
    iosBundleId: 'com.example.secretMissionApp',
  );
}
